version: '2'
services:
  freejekyllbuilder:
    container_name: freejekyllbuilder
    build: .
    ports: 
      - "443:9004"
    volumes:
      - ./server/:/opt/freejekyllbuilder
      - ./files/:/opt/files
      - ./boundary/:/opt/boundary
      - ./webroot/:/opt/webroot
    environment:
      - VIRTUAL_HOST=freejekyllbuilder.com,www.freejekyllbuilder.com


## For use with nginx-proxy
#networks:
#  default:
#    external:
#      name: nginx-proxy

