#!/bin/bash
echo hello i am meta self deploy
echo cd /tmp
cd /tmp

echo rm metaself
rm metaself

echo rm -rf _site
rm -rf _site

echo wget freejekyllbuilder.com/download/metaself
wget freejekyllbuilder.com/download/metaself

echo unzip metaself
unzip metaself


echo this happens in the container
echo delete existing deploymenet
rm -rf /opt/webroot/*
echo deploy
mv _site/* /opt/webroot/
echo cleanup
rm metaself

